version: '3.8'

# TOP-LEVEL NETWORKS
networks:
  football-net:
    driver: bridge

# TOP-LEVEL VOLUMES
volumes:
  prometheus_data:
  grafana_data:
  jenkins_data:

services:
  #Kong API Gateway (DB-less)
  kong:
    image: kong:3.4-ubuntu
    container_name: football-kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml:ro
    ports:
      - "8000:8000"   # Gateway Entry Point for Frontend Requests
      - "8001:8001"   # Kong Admin API
    depends_on:
      - football-backend
    networks:
      - football-net

  football-backend:
    build: ./backend
    container_name: football-backend
    ports:
      - "8080:8080"
    environment:
      - API_SPORTS_KEY=${API_SPORTS_KEY}
    networks:
      - football-net

  football-frontend:
    build: ./frontend     # Looks for ./frontend/Dockerfile
    container_name: football-frontend
    ports:
      - "3000:80"
    depends_on:
      - football-backend
    networks:
      - football-net

  prometheus:
    image: prom/prometheus:latest
    container_name: football-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - football-net

  grafana:
    image: grafana/grafana:latest
    container_name: football-grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - football-net

  jenkins:
    image: jenkins/jenkins:lts
    container_name: football-jenkins
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - football-net